name: smart_parking_app
description: A Smart Parking App using Flutter and MongoDB
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  http: ^1.4.0
  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.2
  flutter_polyline_points: ^2.1.0
  intl: ^0.20.2
  flutter_stripe: ^11.5.0
  flutter_dotenv: ^5.1.0
  dio: ^5.1.2
  flutter_secure_storage: ^9.2.4
  mongo_dart: ^0.10.5
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
